= Terminology

// please mark all terms in description italic that are described individually in this document

[[answer]]Answer::
An answer contains the students files/solution for a single _Task_.

[[assignment]]Assignment::
An assignment groups multiple _Tasks_. It has a title, start-date, deadline and some other meta-data. In real life it would be some form of worksheet you give to students.

[[containers]](Docker) Containers::
Containers are isolated processes that run on Linux machines. They are always based on an _Image_. Containers allow secure execution of submitted code.

[[evaluation]]Evaluation::
An _Evaluation_ is the result of a executed _Evaluation Definition_ on a students _Answer_. It consists of multiple _Evaluation Steps_ that have been executed by _Evaluation Runners_.

[[evaluation-definition]]Evaluation Definition::
The _Evaluation Definition_ refers to the contents of the `codefreak.yml` file. It defines which _Evaluation Runners_ should be run on an _Answer_ and the configuration for them.

[[evaluation-runner]]Evaluation Runner::
An _Evaluation Runner_ executes the automated evaluation of source code. There are different types of runners that accept different forms of configuration. Runners are always executed in _Containers_.

[[evaluation-step]]Evaluation Step::
An _Evaluation Step_ groups all _Feedback_ that has been generated by an _Evaluation Runner_ by testing the submitted source code. The result of an _Evaluation Step_ can be "successful" or "failed". The step is only successful if all _Feedback_ is "successful".

[[feedback]]Feedback::
The smallest unit in the evaluation context is _Feedback_. It consists at least of a single "summary" that gives some helpful feedback on an _Answer_. A _Feedback_ optionally refers to a file or parts of it. _Feedback_ is generated automatically by all evaluation runners or can be created manually by creating comments.

[[image]](Docker) Image::
An _Image_ is the boilerplate for _Containers_. It contains all files that form a basic filesystem and some default instructions to run in containers.

[[submission]]Submission::
A submission groups all _Answers_ of a single User for one _Assignment_.

[[task]]Task::
A task contains the boilerplate code the students start working on and the _Evaluation Definition_.

[[task-pool]]Task Pool::
As a teacher you might use the same _Tasks_ over and over again in different _Assignments_ and/or semesters. The _Task Pool_ allows you to define _Tasks_ once and use them in different _Assignments_.
