= Configuration

For more details on configuration please check the https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files[Spring documentation].

== Authentication
Code FREAK provides multiple ways to authenticate users. You can choose one of the following methods to integrate the application with your existing infrastructure.

=== Simple Authentication
Simple authentication means that users are managed by Code FREAK itself. Accounts are created by administrators and saved to the database.

WARNING: Simple authentication has not been implemented yet! It only works in `dev` mode with preconfigured users. See https://github.com/codefreak/codefreak/issues/122[Issue #122] for progress.

[source,yaml]
----
codefreak.authentication-method: simple # this is the default
----

=== LDAP
Code FREAK can connect to an LDAP server and use it for authentication. A minimal configuration requires the URL of the server and a mapping from LDAP groups to Code FREAK roles.

As an example, you can find an LDAP test server https://github.com/rroemhild/docker-test-openldap[here]. It can be used with the following configuration.

[source,yaml]
----
codefreak:
  authentication-method: ldap
  ldap:
    url: ldap://127.0.0.1:389
    root-dn: dc=planetexpress,dc=com
    group-search-base: ou=people
    role-mappings.admin_staff: admin
    role-mappings.ship_crew: student
    #active-directory: true (set this if you are using an Active Directory server)
----

== Git import
You can allow your students to import their source code from a remote Git repository. Currently, this is possible only via a
shared SSH key that has access to all repositories on the Git server. Some Git servers allow this by using so-called
"deployment keys". You can configure multiple hosts but only one SSH key per host. Students have to use the clone URL
starting with `ssh://` when importing from the remote repository. Import via HTTP is not possible currently.

[source,yaml]
----
codefreak:
    git-import:
      enabled: true
      remotes:
      - host: git.example.org
        ssh-key: /path/to/ssh/id_rsa
        ssh-key-pass: securepassword123
        ssh-base-url: ssh://git@git.example.org
----
