= LTI 1.3 Support

WARNING: LTI integration is broken currently, sorry.

Code FREAK supports integration with Learn Management Systems (LMS) like Moodle or Canvas via the LTI 1.3 standard.
Before you begin make sure your LMS supports the LTI 1.3 standard. LTI 1.0 and 2.0 are *NOT* supported!
You need the following information from your LMS:

* LTI authentication URL
* LTI/OAuth 2.0 token URL
* URL to receive the JWK-set of the LMS
* A client ID (should be generated by your LMS when registering an external tool)

In addition you need to create an RSA keypair and put them into a Java key store. This is required
to cryptographically sign the messages send between Code FREAK and the LMS.

== Configuration

=== Generate the RSA key pair and Java key store
The following instructions will show you how to generate an RSA key pair with the Java `keytool` and how to
extract the public key (often needed for you LMS) with `openssl`.
You will need to have `openssl` and the JDK's `keytool` installed. Please consult a search engine of your choice
how to do this for your platform.

==== Generate the keystore:
This will create a file called `cf-keys.pkcs12` with a public/private key pair.

[source]
----
$ keytool -genkey \
  -keystore cf-keys.p12 \
  -storetype pkcs12 \
  -storepass "supersecurepassword123" \
  -keyalg RSA \
  -alias codefreak \
  -validity 10950
----

==== Export public key in PEM format:
This will extract the public key (without certificate information) from the pkcs12 file you just created.
You may need this information when registering Code FREAK as external tool in your CMS.

[source]
----
$ openssl pkcs12 -in cf-keys.p12 -nokeys | openssl x509 -pubkey -noout
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQE ...
----

==== Register Code FREAK as LTI Tool
Please check the manual of your LMS how to register external LTI 1.3 Tools. If required please use the following
information.

Please replace `[codefreak-url]` with the public accessible URL of your Code FREAK installation including `http(s)://...`


|===
|Attribute |Value

|Tool Name
|Code FREAK

|Tool URL
|`[codefreak-url]`

|LTI Version
|1.3

|Public key
|The exported public key from the previous step

|Login URL
|`[codefreak-url]/lti/login`

|Redirect URLs
|`[codefreak-url]/lti/launch`

|Deep Linking (Content Selection) URL
|`[codefreak-url]/lti/select-content`

|Icon URL
|`[codefreak-url]/images/lti-code-icon.png`
|===

WARNING: Please make sure your LMS passes the user's name and email address to Code FREAK! Some LMS have additional privacy settings for these options.

The LMS should generate a Client ID for you. Please write it down for the next step.

==== Configuring Code FREAK for LTI
Please put the key store file in a location where the Code FREAK process can read it. If you are running
Code FREAK with Docker you may have to mount the generated key store as volume inside the container.

Adjust the configuration with all the information you received from your LMS. The following is an example
that should work with Moodle 3.7 and later:

[source,yaml]
----
codefreak:
  lti:
    enabled: true
    key-store: file:/path/to/your/keystore/cf-keys.p12
    key-store-type: PKCS12
    # for pkcs12 key stores the store password and entry pin are always the same
    key-store-password: supersecurepassword123
    providers:
      - name: Some human-readable name
        issuer: "https://lms.example.org"
        client-id: client-id-from-your-lms
        auth-url: "https://lms.example.org/mod/lti/auth.php"
        token-url: "https://lms.example.org/mod/lti/token.php"
        jwk-url: "https://lms.example.org/mod/lti/certs.php"
        key-store-entry-name: codefreak
        key-store-entry-pin: supersecurepassword123
----
