= Development environment setup
:sectnums:
:toc: left
:toclevels: 3

== Configuration
Create a file `src/main/resources/application-dev.yml`. For documentation on how to configure the
server see https://github.com/code-freak/code-freak/blob/master/src/main/resources/application.yml[`application.yml`]
in the same directory. Minimum configuration that uses the in-memory database:
```yaml
spring:
  jpa:
    database: HSQL
    hibernate:
      ddl-auto: create
```

=== Database
You can either use the embedded HSQL storage or a PostgreSQL database. Data from the HSQL database will get lost when
the application shuts down. For Postgres create at least a dedicated database and adjust the configuration accordingly:
```yaml
spring:
  datasource:
    url: "jdbc:postgresql://[host]:[port]/database"
    username: user
    pasword: supersecure
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
```

=== Docker
For many parts of the application we need connection to a (dedicated) Docker daemon. By default we use the default
socket for your platform. If you are on Linux please follow the installation guidelines for your distribution.
For Windows, MacOS and other OS that cannot run Docker natively you will either need the official Docker for Windows/MacOS
software stacks or use the Vagrant machine that is included in this repository. The Vagrant machine will make the Docker
daemon available at `127.0.0.1:2375` (the official Docker port). If you setup Docker for Windows/MacOS the Daemon should
be reachable on the same address. So if you are on Windows or MacOS adjust your `application-dev.properties` file so it points
at a Docker daemon.
```yaml
code-freak:
  docker:
    host: "tcp://127.0.0.1:2375"
```

== Run the application
If you use IntelliJ simply start the `CodeFreakApplication` Spring Boot application.
For Gradle run the command `./gradlew bootRun`. The application is started at `http://localhost:8080`.

== Authentication
The following sample users are pre-configured for development.

.Sample Users
|===
|Username |Password |Role

|admin
|123
|ADMIN

|teacher
|123
|TEACHER

|student
|123
|STUDENT
|===

== Running tests
To run the tests you need a working Docker connection. It is also possible to use the Vagrant machine for Testing:
```shell
$ ./gradlew test          # for testing with local Docker daemon
$ ./gradlew vagrantTest   # for testing with Vagrant Docker daemon
```

== Fix linting issues
```console
$ ./gradlew spotlessApply
```
