= Code FREAK Documentation
:sectnums:
:toc: left
:toclevels: 3

:toc!:

Welcome to the Code FREAK documentation.
Code FREAK is an online IDE for educational purposes that allows teachers to create and enroll programming tasks
allows students to programm and execute their code without leaving the browser. Submissions can be evaluated
automatically by various testing-methods like unit tests or code smell detection.

WARNING: Code FREAK is under heavy development. Things might break between updates even if we try to be backwards-compatible.

== Getting started
If you are new to Code FREAK here are some links that may help you to understand the basic concepts of the system:

* link:architecture.adoc[Architecture of Code FREAK]
* link:development.adoc[Development Setup]
* More resources coming soon...

== Security
We utilize Linux containers based on Docker which allow a good logical isolation (separate process-set, resource-limits, …).
It should be very difficult to escape from the containers and do harm to the underlying host-system but we do not guarantee
that it is impossible. This is why we recommend to run a dedicated Docker daemon only for Code FREAK that does nothing
else except hosting the IDE instances and running untrusted code.
Additionally you should not run the Code FREAK application and its sidekick Docker daemon on the same host for similar
reasons: If someone manages to escape the IDE containers they could hijack the backend application and steal sensitive
information. Even if someone does not accomplishes to break out of the container they could spin up so many containers
that all host system resources are exhausted.

== Installation
There are various methods to run the application in production. We only support the Docker/docker-compose setup.
If you plan to run the application directly on a host-system you should know what you are doing. If you are looking
for a development setup please take a look at the <<Development / Contribution>> section.

=== Prerequisites
For the backend application:

* A Docker host/daemon
* About 1-2GB RAM

For the dedicated docker daemon:

* Separated Docker daemon that does not run on the same host as the backend application
* Lots of memory. You should plan 3-4GB RAM per concurrent user (depending on the
programming language). We are working on reducing the RAM usage.
* About CPU 1 Core / concurrent 10 users

=== Preparing the Docker daemon
Docker allows to connect via HTTP/TLS to the integrated API. This requires to set up a PKI for certificate-management.
There is an extensive documentation on how to do this in the official Docker docs.
https://docs.docker.com/engine/security/https/[Please follow this article] carefully. As the result you should have
a `ca.pem`, `cert.pem` and `key.pem` file that can be used on your backend application host.

=== Set up using Docker Compose
We have included a sample `docker-compose.yml` in the main repository. This should work fine out-of-the-box but uses
a Docker-in-Docker container which is not suited for development. Please remove the `docker` service and adjust the
environment-variables of the `app` service that it points to your dedicated Docker host. Place the `ca.pem`, `cert.pem`
and `key.pem` files in a directoy `certificates` next to your `docker-compose.yml` and adjust the configuration
accordingly:

```yaml
version: "3"
services:
  app:
    # ... SNIP ...
    volumes:
      - "./certificates:/var/code-freak/certs"
    environment:
      DOCKER_HOST: "http://docker-host.at-your-company.domain.com:2376"
      DOCKER_CERT_PATH: "/var/code-freak/certs"
      # ... SNIP ...
```

== Configuration
`TODO`

== Development / Contribution
`TODO`

== License
Code FREAK is licensed under the AGPLv3. For more information see the LICENSE file that comes with the source code.
